const { chapterRefFromTitle, formatMarkdownTable, loadControlPlane, replaceAutoGeneratedBlock, writeText, loadText } = require('./knowledge-lib.js');

const graph = JSON.parse(loadText('generated/graph.json'));
const { learningStages, optimizationAxes } = loadControlPlane();
const coreNodes = graph.nodes
  .filter((node) => node.file && node.metadata?.source_scope === 'core')
  .sort((left, right) => left.metadata.display_order - right.metadata.display_order);

const stageRows = learningStages.stages.map((stage) => {
  const stageNodes = coreNodes.filter((node) => node.metadata.learning_stage === stage.name);
  const chapters = stageNodes.map((node) => chapterRefFromTitle(node.metadata.title)).join('、') || '—';
  const axes = Array.from(
    new Set(stageNodes.flatMap((node) => node.metadata.optimization_axes || []))
  ).join('、') || '—';
  return [stage.name, chapters, stage.description, axes];
});

const axisNames = optimizationAxes.axes.map((axis) => axis.name);
const axisRows = coreNodes.map((node) => [
  chapterRefFromTitle(node.metadata.title),
  ...axisNames.map((axis) => (node.metadata.optimization_axes.includes(axis) ? '●' : ''))
]);

const lines = [
  '# Generated Learning Path',
  '',
  '> Auto-generated from metadata. Changing `learning_stage` or `optimization_axes` will update this page.',
  '',
  '## 阶段路线图',
  '',
  ...formatMarkdownTable(['阶段', '章节', '阶段目标', '重点优化轴'], stageRows),
  '',
  '## 优化目标矩阵',
  '',
  ...formatMarkdownTable(['章节', ...axisNames], axisRows)
];

writeText('generated/path.md', `${lines.join('\n')}\n`);

replaceAutoGeneratedBlock('visualizations/path-overview.md', 'PATH', [
  '## 自动生成：阶段路线图',
  '',
  ...formatMarkdownTable(['阶段', '章节', '阶段目标', '重点优化轴'], stageRows),
  '',
  '## 自动生成：优化目标矩阵',
  '',
  ...formatMarkdownTable(['章节', ...axisNames], axisRows)
]);

console.log('generated/path.md created');
